### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [howell33/my_new_app#1]
This looks mostly very good, but there are quite a few hard-tabs and inconsistent indentation throughout this project. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by howell33** [comment]
yea ive been trying to just fix the errors that pop up but I'm just gonna redo the entire thing

**Comment by chrisvfritz** [comment]
Sorry to hear that. :cry: Remember that I'd still be happy to meet tomorrow if you wanted to.

**Comment by howell33** [comment]
Think I fixed everything now.

**Comment by chrisvfritz** [comment]
It definitely does look better, but I still see hard tabs in these files:
- `Gemfile`
- `app/assets/stylesheets/static.css`
- `app/controllers/static_controller.rb`
- `app/helpers/static_helper.rb`

**Comment by howell33** [comment]
updated

**Comment by chrisvfritz** [comment]
:+1: Marvelous!
